import { useState, useEffect, useRef } from 'react';
import { Audio } from 'expo-av';

export const useAudioLevel = () => {
  const [dbLevel, setDbLevel] = useState(0);
  const [isMonitoring, setIsMonitoring] = useState(false);
  const recordingRef = useRef(null);

  const startMonitoring = async () => {
    try {
      // Request microphone permission
      const permission = await Audio.requestPermissionsAsync();
      if (permission.status !== 'granted') {
        console.error('Permissão de microfone não concedida.');
        return;
      }

      // Configure audio mode
      await Audio.setAudioModeAsync({
        allowsRecordingIOS: true,
        playsInSilentModeIOS: true,
      });

      // Create recording with metering enabled
      const { recording } = await Audio.Recording.createAsync(
        {
          isMeteringEnabled: true, // Crucial for getting decibels
          android: {
            extension: '.m4a',
            outputFormat: Audio.AndroidOutputFormat.MPEG_4,
            audioEncoder: Audio.AndroidAudioEncoder.AAC,
            sampleRate: 44100,
            numberOfChannels: 1,
            bitRate: 128000,
          },
          ios: {
            extension: '.m4a',
            outputFormat: Audio.IOSOutputFormat.MPEG4AAC,
            audioQuality: Audio.IOSAudioQuality.MIN,
            sampleRate: 44100,
            numberOfChannels: 1,
            bitRate: 128000,
            linearPCMBitDepth: 16,
            linearPCMIsBigEndian: false,
            linearPCMIsFloat: false,
          },
          web: {},
        },
        (status) => {
          if (status.metering !== undefined && status.metering !== null) {
            // status.metering ranges from -160 (silence) to 0 (maximum volume)
            // Convert to a positive decibel scale (approx 30 dB to 120 dB)
            const db = Math.round(160 + status.metering);
            setDbLevel(db);
          }
        },
        500 // status update interval in milliseconds
      );

      recordingRef.current = recording;
      setIsMonitoring(true);
    } catch (error) {
      console.error('Falha ao iniciar monitoramento de áudio:', error);
      setIsMonitoring(false);
    }
  };

  const stopMonitoring = async () => {
    if (recordingRef.current) {
      try {
        await recordingRef.current.stopAndUnloadAsync();
        // Delete the temporary file generated by the recording to save space
        const uri = recordingRef.current.getURI();
        if (uri) {
          // If we had file system access we'd delete it, but unloading is enough to release native resource
          console.log('Gravação finalizada e descarregada.');
        }
      } catch (error) {
        console.error('Erro ao parar monitoramento de áudio:', error);
      } finally {
        recordingRef.current = null;
        setIsMonitoring(false);
        setDbLevel(0);
      }
    }
  };

  // Clean up on unmount
  useEffect(() => {
    return () => {
      if (recordingRef.current) {
        recordingRef.current.stopAndUnloadAsync().catch((err) => console.log('Cleanup error:', err));
      }
    };
  }, []);

  return {
    dbLevel,
    isMonitoring,
    startMonitoring,
    stopMonitoring,
  };
};
